---
- name: Check and install docker
  hosts: app
  become: true
  tasks:
    - name: Check if openssh and opensll is installed
      package:
        name: "{{item}}"
        state: present
      loop:
        - openssh-server
        - openssl
    - name: Check if docker is installed
      shell: docker --version
      register: docker_installed
      ignore_errors: yes
    - ansible.builtin.debug:
        var: docker_installed
    - name: Install Docker
      shell: 
        sudo yum install docker -y
      when: docker_installed is failed
    - name: check docker version
      shell: docker --version
      register: docker_version
    - ansible.builtin.debug:
        var: docker_version
        

