---


- name: start an instance with a public IP address
  amazon.aws.ec2_instance:
    access_key: "{{access_key}}"
    aws_secret_access_key: "{{aws_secret_access_key}}"
    name: "public-compute-instance"
    key_name: "Dev"                            #provide key pair name
    region: "{{region}}"                     #provide region
    vpc_subnet_id: "{{vpc_subnet_id}}"    #provide Subnet ID
    instance_type: "{{instance_type}}"
    security_group: "{{security_group}}"   #provide security group id of region
    network_interfaces:
      - assign_public_ip: true
    image_id: ami-051821c6674233b27
